/**
 * API 模块入口
 * 自动生成，请勿手动修改
 */

export * from './types'

export * from './builtin'
export * from './plugins'
export * from './clientConfig'
export * from './accountVerification'
export * from './banners'
export * from './careerStats'
export * from './challenges'
export * from './champSelectLegacy'
export * from './champSelect'
export * from './champions'
export * from './chat'
export * from './clash'
export * from './collections'
export * from './cosmetics'
export * from './endOfGame'
export * from './gameClientChat'
export * from './gameQueues'
export * from './gameSettings'
export * from './gameflow'
export * from './highlights'
export * from './honorV2'
export * from './inventory'
export * from './krShutdownLaw'
export * from './licenseAgreement'
export * from './loadouts'
export * from './lobbyTeamBuilder'
export * from './lobby'
export * from './login'
export * from './loot'
export * from './maps'
export * from './matchHistory'
export * from './matchmaking'
export * from './missions'
export * from './npeRewards'
export * from './npeTutorialPath'
export * from './patch'
export * from './perks'
export * from './personalizedOffers'
export * from './playerBehavior'
export * from './playerPreferences'
export * from './premadeVoice'
export * from './purchaseWidget'
export * from './ranked'
export * from './regalia'
export * from './replays'
export * from './rms'
export * from './rsoAuth'
export * from './settings'
export * from './spectator'
export * from './statstones'
export * from './store'
export * from './summoner'
export * from './patcher'
export * from './playerNotifications'
export * from './manager'
export * from './tracing'
export * from './voiceChat'
export * from './other'